name             'gitlist'
maintainer       'Ryan Lovelett'
maintainer_email 'ryan@lovelett.me'
license          'MIT'
description      'Installs/Configures gitlist'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.0.1'

depends          'git'
depends          'apache2'
depends          'php'
depends          'phpunit'
depends          'composer'
depends          'build-essential'
depends          'pdepend'
depends          'phpcpd'
depends          'phploc'
depends          'phpmd'
